# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singlestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('cap', models.CharField(max_length=20)),
                ('last_trade_price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('yearly', models.FloatField()),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
                ('qa', models.FloatField()),
            ],
        ),
    ]
