# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlestock',
            name='qa',
        ),
        migrations.AddField(
            model_name='singlestock',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
