# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('s1', models.CharField(max_length=50)),
                ('s2', models.CharField(max_length=50)),
                ('s3', models.CharField(max_length=50)),
                ('s4', models.CharField(max_length=50)),
                ('s5', models.CharField(max_length=50)),
                ('s6', models.CharField(max_length=50)),
                ('s7', models.CharField(max_length=50)),
                ('s8', models.CharField(max_length=50)),
                ('s9', models.CharField(max_length=50)),
                ('s10', models.CharField(max_length=50)),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='testmodel',
        ),
    ]
