# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20170906_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s10',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s9',
        ),
        migrations.AddField(
            model_name='profile',
            name='stocks',
            field=models.ManyToManyField(to='stock.singlestock'),
        ),
    ]
