# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170919_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
